Event page linked to every event of the site
WildCodeSchool-2024-09/JS-Nantes-P2-Nant-Event pull request #28
Opened 2024-11-25 15:45 UTC by vloiseau13

2024-11-25 16:19 UTC, MrLootman requested changes

2024-11-25 16:19 UTC, MrLootman commented on client/src/components/Calendar.tsx
> +                        src="../../public/koala.jpg"
`src="/koala.jpg"`

2024-11-25 16:19 UTC, MrLootman commented on client/src/components/SportPage.tsx
>  interface EventData {
Importance de ne pas dupliquer les interfaces à travers le projet.
Ces interfaces, qui apparaissent également dans `MusicPage`, doivent être réunies dans un fichier pour n'être créées qu'une seule fois.

2024-11-25 16:19 UTC, MrLootman commented on client/src/pages/Evenement.tsx
> +      <div>
Cette `div` englobante à celle du sens ?
Si non... On évite de charger le DOM d'éléments non sémantiques.

2024-11-27 10:38 UTC, Jeremy-Mrz requested changes

2024-11-27 10:38 UTC, Jeremy-Mrz commented on client/src/components/MapCard.tsx
> +// }
Tu peux supprimer les commentaires

2024-11-27 10:38 UTC, Jeremy-Mrz commented on client/src/components/CardsTheme.tsx
>  }
Comme tu as commencer à centraliser les interfaces, autant déplacer celle-ci aussi

2024-11-27 10:38 UTC, Jeremy-Mrz commented on client/src/main.tsx
> +          ),
Dans ce cas, le loader n'est pas vraiment pertinent.
Ce que tu renvoie dans le loader est une promesse qui se résoudra après le chargement de la page.
Quand on utilise un loader, c'est  généralement pour réaliser des actions (fetch, function) et obtenir un résultat avant que la page soit chargée.
Si tu veux obtenir le résultat du fetch avant de charger la page, il faut déclarer la fonction comme `async` : `loader: async({params}) => ...` et attendre le résultat du fetch `const result = await fetch(....)`.
Tu peux ensuite réaliser l'opération `const data = await result.json()` directement dans le loader, et ne pas oublier de `return data`

2024-11-27 10:55 UTC, Jeremy-Mrz approved these changes

2024-11-27 10:55 UTC, Jeremy-Mrz approved these changes

2024-11-27 10:56 UTC, MrLootman approved these changes

2024-11-27 10:56 UTC, merged