Carousel done, responsive version not completely finished
WildCodeSchool-2024-09/JS-Nantes-P2-Nant-Event pull request #3
Opened 2024-11-08 08:55 UTC by alicepgrd

- Creation of a components folder with a carousel.tsx file and a Data.tsx file (containing images). Creation of a styles folder with a carousel.css file. Deletion of css from app.css; Deletion of elements present during cloning in App.tsx and element added. 
- Creation of the carousel, but the overlay is not yet responsive.

2024-11-08 15:33 UTC, Jeremy-Mrz commented on client/src/App.tsx
> +      {/*carousel*/}
Les class css doivent être écrites en kebab-case, dans ce cas `app`
`{/*carousel*/}` oubli de suppression ?

2024-11-08 15:40 UTC, Jeremy-Mrz requested changes

2024-11-08 15:40 UTC, Jeremy-Mrz commented on client/src/components/Carousel.tsx
> +          {" "}
Est ce que cette ligne a une utilité ?

2024-11-08 15:40 UTC, Jeremy-Mrz commented on client/src/components/Carousel.tsx
> +          {" "}
Idem

2024-11-08 15:40 UTC, Jeremy-Mrz commented on client/src/components/Carousel.tsx
> +                key={_.imgSrc}
Si tu utilises l'élément de ton map, n'utilise pas `_` comme nom

2024-11-08 15:40 UTC, Jeremy-Mrz commented on client/src/styles/Carousel.css
> +}
Pour le style global, il faut créer une fichier global.css

2024-11-12 10:48 UTC, MrLootman approved these changes

2024-11-12 14:49 UTC, Ben5978lab approved these changes
good

2024-11-12 14:49 UTC, merged